name: native_splash_screen_example
description: "Demonstrates how to use the native_splash_screen plugin."
publish_to: 'none'
version: 1.0.0

platforms:
  linux:
  windows:

environment:
  sdk: ^3.7.2
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  native_splash_screen:
    # When depending on this package from a real application you should use:
    #   native_splash_screen_linux: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../


dev_dependencies:
  flutter_lints: ^5.0.0
  native_splash_screen_cli: '>=1.0.0 <2.0.0'

flutter:
  uses-material-design: true
