name: native_splash_screen_windows
description: "Windows implementation of the native_splash_screen plugin."
repository: https://github.com/anicine/native_splash_screen
version: 2.0.0
# homepage:

topics:
  - windows

platforms:
  windows:

environment:
  sdk: ^3.4.0
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  # native_splash_screen_platform_interface: '>=2.0.0 <3.0.0'
  native_splash_screen_platform_interface:
    path: "../native_splash_screen_platform_interface"


flutter:
  plugin:
    implements: native_splash_screen
    platforms:
      windows:
        pluginClass: NativeSplashScreenWindowsPluginCApi

dev_dependencies:
  flutter_lints: